using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class RoomSyncModel 
{
    [RealtimeProperty(2, true, true)]
    private bool _isVisible;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class RoomSyncModel : RealtimeModel {
    public bool isVisible {
        get {
            return _isVisibleProperty.value;
        }
        set {
            if (_isVisibleProperty.value == value) return;
            _isVisibleProperty.value = value;
            InvalidateReliableLength();
            FireIsVisibleDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(RoomSyncModel model, T value);
    public event PropertyChangedHandler<bool> isVisibleDidChange;
    
    public enum PropertyID : uint {
        IsVisible = 2,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _isVisibleProperty;
    
    #endregion
    
    public RoomSyncModel() : base(null) {
        _isVisibleProperty = new ReliableProperty<bool>(2, _isVisible);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _isVisibleProperty.UnsubscribeCallback();
    }
    
    private void FireIsVisibleDidChange(bool value) {
        try {
            isVisibleDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _isVisibleProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _isVisibleProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.IsVisible: {
                    changed = _isVisibleProperty.Read(stream, context);
                    if (changed) FireIsVisibleDidChange(isVisible);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _isVisible = isVisible;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
